TASK/activities/urls.py
from django import urls
from . import views
from django.urls import path

app_name = 'activities'

urlpatterns = [
    path("", views.index, name = 'index'),
    path("add", views.add, name = 'add'),
]

TASK/todolist/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("activities/", include('activities.urls'))
]

TASK/activities/models.py
from django.db import models

# Create your models here.

TASK/activities/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse

class AddList(forms.Form):
    task = forms.CharField(label='Task', max_length=100)

#task_list = []

# Create your views here.
def index(request):
    if "task" not in request.session:
        request.session['task'] = []

    #return HttpResponse('working')
    return render(request, "activities/index.html", {'lol':request.session['task']})

def add(request):
    if request.method == 'POST':
        form = AddList(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['task'] += [task]
            return HttpResponseRedirect(reverse('activities:index'))
        else:
            return render(request, 'activities/add.html', {'form':form})

    return render(request, "activities/add.html", {'form':AddList()})

TASK/activities/templates/activities/add.html
{% extends 'activities/base.html' %}

{% block body %}
    <h1>Add Task</h1>

    <form action="{% url 'activities:add' %}" method = 'post'>
        {% csrf_token %}
        {{form}}
        <input type="submit"><br>
    </form>

    <a href="{%url 'activities:index' %}">Go back to list</a>
{% endblock %}

TASK/activities/templates/activities/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activities</title>

</head>
<body>
    {% block body%}
        
    {% endblock %}
</body>
</html>

TASK/activities/templates/activities/index.html
{% extends 'activities/base.html' %}

{% block body %}
    <h1>ToDo List</h1>
    <hr>

    {% for taskss in lol %}
        <li>{{taskss}}</li><br>

    {% empty %}
        <h1>Empty Task</h1>

    {% endfor %}

    <a href="{% url 'activities:add' %}">Add List</a>
{% endblock %}